sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - true #authorization 👇
  - gcloud auth activate-service-account --key-file service-account.json
  - true # `service-account.json` above is extremely sensitive content
  - gcloud config set project multi-k8s-396410
  - gcloud config set compute/zone asia-northeast1
  - gcloud container clusters get-credentials multi-cluster-2
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - true # docker build -t nailbiter/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo hi # docker run -e CI=true nailbiter/react-test npm test # could run more (all) tests, but restrict to one for brevity

deploy: # note -- unlike AWS, no built-in provider for k8s
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
