language: generic
sudo: required
services:
  - docker

before_install:
  echo hey
  # - docker build -t nailbiter/react-test -f ./client/Dockerfile.dev client

script: #primary test-running section
  - echo hi
  # - docker run -e CI=true nailbiter/react-test npm test


after_success:
  echo hoy
  #- docker build -t nailbiter/multi-server ./server
  # - docker build -t nailbiter/multi-client ./client
  # - docker build -t nailbiter/multi-worker ./worker
  # - docker build -t nailbiter/multi-nginx ./nginx
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - docker push nailbiter/multi-client
  # - docker push nailbiter/multi-server
  # - docker push nailbiter/multi-worker
  # - docker push nailbiter/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-824059422197'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
