apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/* # skaffold will try to delete all these deployments on exit
build:
  tagPolicy:
    sha256: {}
  local:
    push: true
  artifacts:
    - image: nailbiter/skaffold-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual: #these file are in scope of "mode #2" (see https://docs.google.com/document/d/1ak9uHsHX4MzsI7ekTf_aj_qD9LnletujIDXLqE0Tg0w/edit#heading=h.wzq7zaf0pqmd); every change beyond these extension will fall in scope of Skaffold's "mode 1"
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .
    - image: nailbiter/skaffold-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: nailbiter/skaffold-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
